import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <title>YoinkUI</title>
        <meta name="description" content="Copy any UI in just one click" />
        <meta name="twitter:card" content="summary_large_image"/>
        <meta name="twitter:site" content="@kiannn.k"/>
        <meta name="twitter:creator" content="@kiannn.k" />
        <meta name="twitter:title" content="YoinkUI" />
        <meta name="twitter:description" content="Copy any UI in just one click" />
        <meta name="twitter:image" content="/twitterCard.png"></meta>
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
