export const inheritableCss = [
  "color",
  "font-family",
  "font-size",
  "font-weight",
  "font-style",
  "font-variant",
  "letter-spacing",
  "line-height",
  "text-align",
  "text-wrap",
  "text-indent",
  "text-transform",
  "visibility",
  "white-space",
  "word-spacing",
  "list-style-type",
];

export const propsToArbitraryMap = {
  "margin-top": "mt",
  "margin-right": "mr",
  "margin-bottom": "mb",
  "margin-left": "ml",
  "scroll-margin-top": "scroll-mt",
  "scroll-margin-right": "scroll-mr",
  "scroll-margin-bottom": "scroll-mb",
  "scroll-margin-left": "scroll-ml",
  "padding-top": "pt",
  "padding-right": "pr",
  "padding-bottom": "pb",
  "padding-left": "pl",
  "scroll-padding-top": "scroll-pt",
  "scroll-padding-right": "scroll-pr",
  "scroll-padding-bottom": "scroll-pb",
  "scroll-padding-left": "scroll-pl",
  color: "text",
  // "text-decoration-color": "decoration", figure out later
  "line-height": "leading",
  "letter-spacing": "tracking",
  width: "w",
  height: "h",
  "min-width": "min-w",
  "min-height": "min-h",
  "max-width": "max-w",
  "max-height": "max-h",
  "border-top-right-radius": "rounded-tr",
  "border-top-left-radius": "rounded-tl",
  "border-bottom-right-radius": "rounded-br",
  "border-bottom-left-radius": "rounded-bl",
  "border-bottom-color": "border-b",
  "border-bottom-width": "border-b",
  "border-left-color": "border-l",
  "border-left-width": "border-l",
  "border-top-color": "border-t",
  "border-top-width": "border-t",
  "border-right-width": "border-r",
  "border-right-color": "border-r",
  transform: "transform",
  "transform-style": "transform-style",
  perspective: "perspective",
  "perspective-origin": "perspective-origin",
  "aspect-ratio": "aspect",
  "list-style-image": "list-image",
  top: "top",
  right: "right",
  bottom: "bottom",
  left: "left",
  "z-index": "z",
  columns: "columns",
  "row-gap": "gap-y",
  "column-gap": "gap-x",
  "grid-template-columns": "grid-cols",
  "grid-template-rows": "grid-rows",
  "font-size": "text",
  "font-family": "font",
  "background-color": "bg", // this gets checked twice
  "background-position": "bg-position",
  "background-size": "bg-size",
  "background-image": "bg",
  "box-shadow": "shadow",
  opacity: "opacity",
  "text-indent": "indent",
  "text-shadow": "text-shadow", // arbitrary needed
  "flex-grow": "grow",
  "flex-shrink": "shrink",
  order: "order",
  "outline-color": "outline", // this gets checked twice
  "outline-width": "outline",
  "outline-style": "outline",
  fill: "fill", // this gets checked twice
  "stroke-width": "stroke",
  stroke: "stroke",
  "stroke-opacity": "stroke-opacity",
  "fill-opacity": "fill-opacity",
  "mask-image": "mask",
  "mask-size": "mask-size",
  "mask-position": "mask-position",
  "object-position": "object",
};

export const directMappings: { [key: string]: { [subkey: string]: string } } = {
  display: {
    block: "block",
    flex: "flex",
    grid: "grid",
    none: "hidden",
    "inline-block": "inline-block",
    inline: "inline",
    "inline-flex": "inline-flex",
    "inline-grid": "inline-grid",
    contents: "contents",
  },
  isolation: {
    auto: "isolation-auto",
    isolate: "isolate",
  },
  "background-attachment": {
    fixed: "bg-fixed",
    local: "bg-local",
    scroll: "bg-scroll",
  },
  "background-clip": {
    "border-box": "bg-clip-border",
    "padding-box": "bg-clip-padding",
    "content-box": "bg-clip-content",
    text: "bg-clip-text",
  },
  "background-origin": {
    "border-box": "bg-origin-border",
    "padding-box": "bg-origin-padding",
    "content-box": "bg-origin-content",
  },
  "background-repeat": {
    repeat: "bg-repeat",
    "repeat-x": "bg-repeat-x",
    "repeat-y": "bg-repeat-y",
    space: "bg-space",
    round: "bg-round",
    "no-repeat": "no-repeat",
  },
  "box-sizing": {
    "border-box": "box-border",
    "content-box": "box-content",
  },
  "mix-blend-mode": {
    normal: "mix-blend-normal",
    multiply: "mix-blend-multiply",
    screen: "mix-blend-screen",
    overlay: "mix-blend-overlay",
    darken: "mix-blend-darken",
    lighten: "mix-blend-lighten",
    "color-dodge": "mix-blend-color-dodge",
    "color-burn": "mix-blend-color-burn",
    "hard-light": "mix-blend-hard-light",
    "soft-light": "mix-blend-soft-light",
    difference: "mix-blend-difference",
    exclusion: "mix-blend-exclusion",
    hue: "mix-blend-hue",
    saturation: "mix-blend-saturation",
    color: "mix-blend-color",
    luminosity: "mix-blend-luminosity",
    "plus-darker": "mix-blend-plus-darker",
    "plus-lighter": "mix-blend-plus-lighter",
  },
  "background-blend-mode": {
    normal: "bg-blend-normal",
    multiply: "bg-blend-multiply",
    screen: "bg-blend-screen",
    overlay: "bg-blend-overlay",
    darken: "bg-blend-darken",
    lighten: "bg-blend-lighten",
    "color-dodge": "bg-blend-color-dodge",
    "color-burn": "bg-blend-color-burn",
    "hard-light": "bg-blend-hard-light",
    "soft-light": "bg-blend-soft-light",
    difference: "bg-blend-difference",
    exclusion: "bg-blend-exclusion",
    hue: "bg-blend-hue",
    saturation: "bg-blend-saturation",
    color: "bg-blend-color",
    luminosity: "bg-blend-luminosity",
    "plus-darker": "bg-blend-plus-darker",
    "plus-lighter": "bg-blend-plus-lighter",
  },
  "mask-clip": {
    "border-box": "mask-clip-border",
    "padding-box": "mask-clip-padding",
    "content-box": "mask-clip-content",
    "fill-box": "mask-clip-fill",
    "stroke-box": "mask-clip-stroke",
    "view-box": "mask-clip-view",
    "no-clip": "mask-no-clip",
  },
  "mask-composite": {
    add: "mask-add",
    subtract: "mask-subtract",
    intersect: "mask-intersect",
    exclude: "mask-exclude",
  },
  "mask-mode": {
    alpha: "mask-alpha",
    luminance: "mask-luminance",
    "match-source": "mask-match",
  },
  "mask-origin": {
    "border-box": "mask-origin-border",
    "padding-box": "mask-origin-padding",
    "content-box": "mask-origin-content",
    "fill-box": "mask-origin-fill",
    "stroke-box": "mask-origin-stroke",
    "view-box": "mask-origin-view",
  },
  "mask-repeat": {
    repeat: "mask-repeat",
    "no-repeat": "mask-no-repeat",
    "repeat-x": "mask-repeat-x",
    "repeat-y": "mask-repeat-y",
    space: "mask-repeat-space",
    round: "mask-repeat-round",
  },
  "mask-type": {
    alpha: "mask-type-alpha",
    luminance: "mask-type-luminance",
  },
  position: {
    static: "static",
    relative: "relative",
    absolute: "absolute",
    fixed: "fixed",
    sticky: "sticky",
  },
  "word-break": {
    normal: "break-normal",
    "break-all": "break-all",
    "keep-all": "break-keep",
  },
  "text-align": {
    left: "text-left",
    center: "text-center",
    right: "text-right",
    justify: "text-justify",
  },
  "text-wrap": {
    wrap: "text-wrap",
    nowrap: "text-nowrap",
    balance: "text-balance",
    pretty: "text-pretty",
  },
  "font-weight": {
    "100": "font-thin",
    "200": "font-extralight",
    "300": "font-light",
    "400": "font-normal",
    "500": "font-medium",
    "600": "font-semibold",
    "700": "font-bold",
    "800": "font-extrabold",
    "900": "font-black",
  },
  "border-style": {
    none: "border-none",
    // "solid": "border-solid",
    dashed: "border-dashed",
    dotted: "border-dotted",
    double: "border-double",
  },
  "text-transform": {
    none: "normal-case",
    capitalize: "capitalize",
    uppercase: "uppercase",
    lowercase: "lowercase",
  },
  "white-space": {
    normal: "whitespace-normal",
    nowrap: "whitespace-nowrap",
    "pre-wrap": "whitespace-pre-wrap",
    pre: "whitespace-pre",
    "pre-line": "whitespace-pre-line",
  },
  overflow: {
    visible: "overflow-visible",
    hidden: "overflow-hidden",
    scroll: "overflow-scroll",
    clip: "overflow-clip",
    auto: "overflow-auto",
  },
  "overflow-x": {
    visible: "overflow-x-visible",
    hidden: "overflow-x-hidden",
    scroll: "overflow-x-scroll",
    auto: "overflow-x-auto",
    clip: "overflow-x-clip",
  },
  "backface-visibility": {
    hidden: "backface-hidden",
    visible: "backface-visible",
  },
  "overflow-y": {
    visible: "overflow-y-visible",
    hidden: "overflow-y-hidden",
    scroll: "overflow-y-scroll",
    auto: "overflow-y-auto",
    clip: "overflow-y-clip",
  },
  "scroll-behavior": {
    auto: "scroll-auto",
    smooth: "scroll-smooth",
  },
  "text-decoration-line": {
    none: "no-underline",
    underline: "underline",
    "line-through": "line-through",
  },
  "text-overflow": {
    ellipsis: "text-ellipsis",
    clip: "text-clip",
  },
  "text-decoration-style": {
    solid: "decoration-solid",
    double: "decoration-double",
    dotted: "decoration-dotted",
    dashed: "decoration-dashed",
    wavy: "decoration-wavy",
  },
  "font-style": {
    italic: "italic",
    normal: "not-italic",
  },
  "vertical-align": {
    baseline: "align-baseline",
    top: "align-top",
    middle: "align-middle",
    bottom: "align-bottom",
    "text-top": "align-text-top",
    "text-bottom": "align-text-bottom",
    sub: "align-sub",
    super: "align-super",
  },
  "flex-wrap": {
    nowrap: "flex-nowrap",
    wrap: "flex-wrap",
    "wrap-reverse": "flex-wrap-reverse",
  },
  "flex-direction": {
    row: "flex-row",
    "row-reverse": "flex-row-reverse",
    column: "flex-col",
    "column-reverse": "flex-col-reverse",
  },
  "justify-items": {
    start: "justify-items-start",
    end: "justify-items-end",
    "safe end": "justify-items-end-safe",
    center: "justify-items-center",
    "safe center": "justify-items-center-safe",
    stretch: "justify-items-stretch",
    normal: "justify-items-normal",
  },
  "justify-self": {
    auto: "justify-self-auto",
    start: "justify-self-start",
    center: "justify-self-center",
    "safe center": "justify-self-center-safe",
    end: "justify-self-end",
    "safe end": "justify-self-end-safe",
    stretch: "justify-self-stretch",
  },
  "justify-content": {
    normal: "justify-normal",
    "flex-start": "justify-start",
    center: "justify-center",
    "flex-end": "justify-end",
    "space-between": "justify-between",
    "space-around": "justify-around",
    "space-evenly": "justify-evenly",
    stretch: "justify-stretch",
    "safe center": "justify-center-safe",
    "safe end": "justify-end-safe",
  },
  "align-items": {
    stretch: "items-stretch",
    "flex-start": "items-start",
    center: "items-center",
    "safe center": "items-center-safe",
    "flex-end": "items-end",
    "safe flex-end": "items-end-safe",
    baseline: "items-baseline",
    "last baseline": "items-baseline-last",
  },
  "align-content": {
    normal: "content-normal",
    "space-evenly": "content-evenly",
    baseline: "content-baseline",
    stretch: "content-stretch",
    "flex-start": "content-start",
    center: "content-center",
    "flex-end": "content-end",
    "space-between": "content-between",
    "space-around": "content-around",
  },
  "align-self": {
    auto: "self-auto",
    stretch: "self-stretch",
    "flex-start": "self-start",
    center: "self-center",
    "safe center": "self-center-safe",
    "flex-end": "self-end",
    "safe flex-end": "self-end-safe",
    baseline: "self-baseline",
    "last baseline": "self-baseline-last",
  },
  // "object-position": {

  // },
  "break-before": {
    auto: "break-before-auto",
    avoid: "break-before-avoid",
    all: "break-before-all",
    "avoid-page": "break-before-avoid-page",
    page: "break-before-page",
    left: "break-before-left",
    right: "break-before-right",
    column: "break-before-column",
  },
  "break-after": {
    auto: "break-after-auto",
    avoid: "break-after-avoid",
    all: "break-after-all",
    "avoid-page": "break-after-avoid-page",
    page: "break-after-page",
    left: "break-after-left",
    right: "break-after-right",
    column: "break-after-column",
  },
  "break-inside": {
    auto: "break-inside-auto",
    avoid: "break-inside-avoid",
    "avoid-page": "break-inside-avoid-page",
    "avoid-column": "break-inside-avoid-column",
  },
  "box-decoration-break": {
    clone: "box-decoration-clone",
    slice: "box-decoration-slice",
  },
  "overscroll-behavior-x": {
    auto: "overscroll-x-auto",
    contain: "overscroll-x-contain",
    none: "overscroll-x-none",
  },
  "overscroll-behavior-y": {
    auto: "overscroll-y-auto",
    contain: "overscroll-y-contain",
    none: "overscroll-y-none",
  },
  "object-fit": {
    fill: "object-fill",
    contain: "object-contain",
    cover: "object-cover",
    none: "object-none",
    "scale-down": "object-scale-down",
  },

  /* Additional properties */
  "list-style-type": {
    none: "list-none",
    disc: "list-disc",
    decimal: "list-decimal",
  },
  "list-style-position": {
    inside: "list-inside",
    outside: "list-outside",
  },
  cursor: {
    auto: "cursor-auto",
    default: "cursor-default",
    pointer: "cursor-pointer",
    wait: "cursor-wait",
    text: "cursor-text",
    move: "cursor-move",
    "not-allowed": "cursor-not-allowed",
  },
  float: {
    left: "float-left",
    right: "float-right",
    none: "float-none",
  },
  clear: {
    left: "clear-left",
    right: "clear-right",
    both: "clear-both",
    none: "clear-none",
  },
  "table-layout": {
    auto: "table-auto",
    fixed: "table-fixed",
  },
  "border-collapse": {
    collapse: "border-collapse",
    separate: "border-separate",
  },
  visibility: {
    visible: "visible",
    hidden: "invisible",
  },
  "grid-auto-flow": {
    row: "grid-flow-row",
    column: "grid-flow-col",
    dense: "grid-flow-dense",
    "row-dense": "grid-flow-row-dense",
    "col-dense": "grid-flow-col-dense",
  },
  "grid-column-start": {
    auto: "col-start-auto",
    "1": "col-start-1",
    "2": "col-start-2",
    "3": "col-start-3",
    "4": "col-start-4",
    "5": "col-start-5",
    "6": "col-start-6",
    "7": "col-start-7",
    "8": "col-start-8",
    "9": "col-start-9",
    "10": "col-start-10",
    "11": "col-start-11",
    "12": "col-start-12",
    "span 1": "col-span-1",
    "span 2": "col-span-2",
    "span 3": "col-span-3",
    "span 4": "col-span-4",
    "span 5": "col-span-5",
    "span 6": "col-span-6",
    "span 7": "col-span-7",
    "span 9": "col-span-9",
    "span 10": "col-span-10",
    "span 11": "col-span-11",
    "span 12": "col-span-12",
  },
  "grid-column-end": {
    auto: "col-end-auto",
    "-1": "col-end-[-1]",
    "-2": "col-end-[-2]",
    "-3": "col-end-[-3]",
    "-4": "col-end-[-4]",
    "-5": "col-end-[-5]",
    "-6": "col-end-[-6]",
    "-7": "col-end-[-7]",
    "-8": "col-end-[-8]",
    "-9": "col-end-[-9]",
    "-10": "col-end-[-10]",
    "-11": "col-end-[-11]",
    "-12": "col-end-[-12]",
    "1": "col-end-1",
    "2": "col-end-2",
    "3": "col-end-3",
    "4": "col-end-4",
    "5": "col-end-5",
    "6": "col-end-6",
    "7": "col-end-7",
    "8": "col-end-8",
    "9": "col-end-9",
    "10": "col-end-10",
    "11": "col-end-11",
    "12": "col-end-12",
    "span 1": "col-span-1",
    "span 2": "col-span-2",
    "span 3": "col-span-3",
    "span 4": "col-span-4",
    "span 5": "col-span-5",
    "span 6": "col-span-6",
    "span 7": "col-span-7",
    "span 9": "col-span-9",
    "span 10": "col-span-10",
    "span 11": "col-span-11",
    "span 12": "col-span-12",
  },
  "grid-row-start": {
    auto: "row-start-auto",
    "1": "row-start-1",
    "2": "row-start-2",
    "3": "row-start-3",
    "4": "row-start-4",
    "5": "row-start-5",
    "6": "row-start-6",
    "7": "row-start-7",
    "8": "row-start-8",
    "9": "row-start-9",
    "10": "row-start-10",
    "11": "row-start-11",
    "12": "row-start-12",
    "span 1": "row-span-1",
    "span 2": "row-span-2",
    "span 3": "row-span-3",
    "span 4": "row-span-4",
    "span 5": "row-span-5",
    "span 6": "row-span-6",
    "span 7": "row-span-7",
    "span 9": "row-span-9",
    "span 10": "row-span-10",
    "span 11": "row-span-11",
    "span 12": "row-span-12",
  },
  "grid-row-end": {
    auto: "row-end-auto",
    "-1": "row-end-[-1]",
    "-2": "row-end-[-2]",
    "-3": "row-end-[-3]",
    "-4": "row-end-[-4]",
    "-5": "row-end-[-5]",
    "-6": "row-end-[-6]",
    "-7": "row-end-[-7]",
    "-8": "row-end-[-8]",
    "-9": "row-end-[-9]",
    "-10": "row-end-[-10]",
    "-11": "row-end-[-11]",
    "-12": "row-end-[-12]",
    "1": "row-end-1",
    "2": "row-end-2",
    "3": "row-end-3",
    "4": "row-end-4",
    "5": "row-end-5",
    "6": "row-end-6",
    "7": "row-end-7",
    "8": "row-end-8",
    "9": "row-end-9",
    "10": "row-end-10",
    "11": "row-end-11",
    "12": "row-end-12",
    "span 1": "row-span-1",
    "span 2": "row-span-2",
    "span 3": "row-span-3",
    "span 4": "row-span-4",
    "span 5": "row-span-5",
    "span 6": "row-span-6",
    "span 7": "row-span-7",
    "span 9": "row-span-9",
    "span 10": "row-span-10",
    "span 11": "row-span-11",
    "span 12": "row-span-12",
  },
};

export const unmappableProps = [
  "translate",
  "clear",
  "filter",
  "clip-path",
  "backdrop-filter",
];
