// Type for the component styles object
export interface ComponentStyles {
  [uid: string]: {
    base: { [key: string]: string };
    sm: { [key: string]: string };
    md: { [key: string]: string };
    lg: { [key: string]: string };
  };
}

export interface StyleValues {
  width: any;
  height: any;
  color: any;
  padding: any;
  margin: any;
  "margin-top": any;
  "margin-right": any;
  "margin-bottom": any;
  "margin-left": any;
  "scroll-margin-top": any;
  "scroll-margin-right": any;
  "scroll-margin-bottom": any;
  "scroll-margin-left": any;
  "padding-top": any;
  "padding-right": any;
  "padding-bottom": any;
  "padding-left": any;
  "scroll-padding-top": any;
  "scroll-padding-right": any;
  "scroll-padding-bottom": any;
  "scroll-padding-left": any;
  "background-color": any;
  "line-height": any;
  "min-width": any;
  "min-height": any;
  "max-width": any;
  "max-height": any;
  "border-top-right-radius": any;
  "border-top-left-radius": any;
  "border-bottom-right-radius": any;
  "border-bottom-left-radius": any;
  "border-radius": any;
  "border-width": any;
  "border-style": any;
  "border-top-width": any;
  "border-top-style": any;
  "border-right-width": any;
  "border-right-style": any;
  "border-bottom-width": any;
  "border-bottom-style": any;
  "border-left-width": any;
  "border-left-style": any;
  top: any;
  right: any;
  bottom: any;
  left: any;
  "z-index": any;
  gap: any;
  "row-gap": any;
  "column-gap": any;
  "grid-template-columns": any;
  "grid-template-rows": any;
  "background-position": any;
  "background-repeat": any;
  "background-size": any;
  "background-image": any;
  "background-clip": any;
  "background-origin": any;
  "background-attachment": any;
  "box-shadow": any;
  "text-wrap": any;
  opacity: any;
  "fill-opacity": any;
  "stroke-opacity": any;
  stroke: any;
  "object-fit": any;
  "text-indent": any;
  columns: any;
  transform: any;
  "transform-style": any;
  perspective: any;
  "perspective-origin": any;
  "backface-visibility": any;
  "text-shadow": any;
  "vertical-align": any;
  "flex-grow": any;
  "flex-shrink": any;
  order: any;
  "scroll-behavior": any;
  display: any;
  "box-sizing": any;
  position: any;
  overflow: any;
  "overflow-x": any;
  "overflow-y": any;
  visibility: any;
  "text-decoration-line": any;
  filter: any;
  "backdrop-filter": any;
  "clip-path": any;
  translate: any;
  "aspect-ratio": any;
  "font-style": any;
  "flex-wrap": any;
  "flex-direction": any;
  "justify-content": any;
  "align-content": any;
  "align-items": any;
  "align-self": any;
  "list-style-type": any;
  cursor: any;
  float: any;
  clear: any;
  "table-layout": any;
  "border-collapse": any;
  "grid-auto-flow": any;
  "grid-column-start": any;
  "grid-column-end": any;
  "grid-row-start": any;
  "grid-row-end": any;
  "outline-style": any;
  "letter-spacing": any;
  "white-space": any;
  "font-weight": any;
  "text-transform": any;
  "font-size": any;
  isolation: any;
  "justify-self": any;
  "justify-items": any;
  "overscroll-behavior-x": any;
  "overscroll-behavior-y": any;
  "box-decoration-break": any;
  "break-inside": any;
  "break-before": any;
  "break-after": any;
  "list-style-image": any;
  "list-style-position": any;
  "text-decoration-color": any;
  "text-decoration-style": any;
  "text-overflow": any;
  "word-break": any;
  "mask-clip": any;
  "mask-composite": any;
  "mask-image": any;
  "mask-mode": any;
  "mask-origin": any;
  "mask-repe": any;
  "mask-position": any;
  "object-position": any;
  "background-blend-mode": any;
  "mix-blend-mode": any;
  "mask-size": any;
  "mask-type": any;
}

export type DeviceKey = "lg" | "md" | "sm";
export type DeviceName = "Desktop" | "Tablet" | "Mobile";
